# conda environment description file for Make-MIDOSS-Forcing package
# development environment
#
# Create a conda environment for development, testing and documentation of the package
# with:
#
#   $ conda env create -f Make-MIDOSS-Forcing/envs/environment-dev.yaml
#   $ source activate make-midoss-forcing
#   (make-midoss-forcing)$ python3 -m pip install --editable Make-MIDOSS-Forcing
#
# See the env/requirements.txt file for an exhaustive list of all of the
# packages installed in the environment and their versions used in
# recent development.

name: make-midoss-forcing

channels:
  - conda-forge

dependencies:
  - bottleneck
  - click
  - h5py
  - netCDF4
  - numpy
  - pip
  - python>=3.6
  - python-dateutil
  - pyyaml
  - xarray

  # For coding style
  - black

  # For unit tests
  - coverage
  - pytest

  # For documentation
  - sphinx
  - sphinx_rtd_theme
